title: Yike的博客
author: Yike
email: vietop09@gmail.com
description: '很高兴能在这里与你分享我修行路上的体验与感悟。' # 站点描述
show_excerpts: true # set to true to show excerpts on the homepage
aboutme: Find my true self


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Yike
  tagline: 修行，冥想，light
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    instagram: kkkkkkkkkkym_
    linkedIn: in/mayike
  sns:
  email: 'mailto:vietop09@gmail.com'
  weibo: '//weibo.com/iaminvincible'

    rss: rss
    # dribbble: mayike
    # facebook: mayike
    # Mastodon instances
    # mastodon:
    # - username: mayike
    #   instance: example.com
    # - username: mayike
    #   instance: example.com

# Search
search: true

# Comments
disqus: true
disqus_url: 'https://yikema.disqus.com/embed.js'

# Reward 赞赏功能 by Ray-Eldath
reward:
  enable: true
  reward_comment: '真诚赞赏 手有余香'
  wechatpay: 'https://yikeemaa.github.io/assets/wechat.png'


# b2t 回到顶部 by Ray-Eldath
b2t: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban']

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed