title: Yike's Blog
author: Yike
email: vietop09@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"

找寻真我，回归源头，成为光与爱。
希望看到的人都能多多少少得到一点启发，鼓励。
We are all ONE. We are Energy and Light!

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Yike Ma
  tagline: 修行者，码农
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: yikeemaa
    github:  yikeemaa
    linkedIn: in/mayike/
    rss: rss
    # dribbble: yikeemaa
    # facebook: yikeemaa
    # flickr:   yikeemaa
    # instagram: Yakima
    # linkedin: yikeemaa
    # pinterest: yikeemaa
    # youtube: yikeemaa
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: +yikeemaa
    # microdotblog: 

    # Mastodon instances
    # mastodon:
    # - username: yikeemaa
    #   instance: example.com
    # - username: yikeemaa
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-slate

plugins:
  - jekyll-seo-tag
#  - jekyll-feed