title: Yike's Blog
author: Yike
email: vietop09@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Yike
  tagline: Coder,Meditator
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: mayike
    github:  mayike
    linkedIn: in/mayike
    rss: rss
    # dribbble: mayike
    # facebook: mayike
    # flickr:   mayike
    # instagram: mayike
    # linkedin: in/mayike
    # pinterest: mayike
    # youtube: mayike
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: mayike
    # telegram: mayike
    # googleplus: +mayike
    # microdotblog: mayike

    # Mastodon instances
    # mastodon:
    # - username: mayike
    #   instance: example.com
    # - username: mayike
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed